# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: duksctf
email: duks.ctf@gmail.com
description: >
    This blog is for hosting writeup from CTF we play in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://duksctf.github.io" # the base hostname & protocol for your site
github_username:  duksctf

# Build settings
markdown: kramdown
kramdown:
  input: GFM

permalink: /blog/:year/:month/:day/:title

gems:
    - jekyll-sitemap
    - jekyll-feed
