# Site settings
title: duksctf
email: redacted
description: > # this means to ignore newlines until "baseurl:"
  This blog is for hosting writeup from CTF we play in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://duksctf.github.io" # the base hostname & protocol for your site
twitter_username: duksctf
github_username:  duksctf

# Build settings
markdown: kramdown

# Permalinks
permalink: /blog/:year/:month/:day/:title

# gems
gems:
  - jekyll-sitemap
