title: ducksctf
description: Bunch of security enthusiasts who sometimes play CTF 
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

